name: Kinetic & Melodic ROS CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os_distro: [[ubuntu-16.04, kinetic], [ubuntu-18.04, melodic]]
    runs-on: ${{ matrix.os_distro[0] }}
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
      ROS_DISTRO: ${{ matrix.os_distro[1] }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/ros1_lifecycle
      #### Rust ####
      - name: Install latest rust
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
      - name: rust version
        run: |
            which rustc
            rustc --version
            which cargo
            cargo --version
      - name: Corrosion
        uses: actions/checkout@v2
        with:
          repository: AndrewGaspar/corrosion
          ref: refs/heads/master
          # submodules: recursive
          path: corrosion
      - name: Build and install Corrosion
        run: |
            pwd
            ls -l
            cmake -Scorrosion -Bbuild_corrosion -DCMAKE_BUILD_TYPE=Release
            cmake --build build_corrosion --config Release
            sudo cmake --install build_corrosion --config Release
      - name: Test Corrosion install
        run: |
            cmake --find-package -DNAME=Corrosion -DCOMPILER_ID=GNU -DLANGUAGE=C -DMODE=EXIST
      - name: roslint
        uses: actions/checkout@v2
        with:
            repository: lucasw/roslint
            ref: roslint_rust
            path: catkin_ws/src/roslint

      ### ROS ###
      - name: Setup for ROS ${{ matrix.os_distro[1] }} install
        run: |
            sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
            sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
            sudo apt-get update -qq
            sudo apt-get install dpkg
      - name: Install ROS basic packages
        run: |
            sudo apt-get install -y python-catkin-pkg
            sudo apt-get install -y python-catkin-tools
            sudo apt-get install -y python-rosdep
            sudo apt-get install -y python-rospkg
            sudo apt-get install -y python-wstool
            sudo apt-get install -y ros-$ROS_DISTRO-ros-base
            # TODO(lucasw) the package.xml + rosdep isn't working for this
            sudo apt-get install -y ros-$ROS_DISTRO-roslint
            source /opt/ros/$ROS_DISTRO/setup.bash
            # Prepare rosdep to install dependencies.
            sudo rosdep init
            rosdep update
      - name: Install ROS additional packages with rosdep
        run: |
            source /opt/ros/$ROS_DISTRO/setup.bash
            cd catkin_ws
            rosdep install --from-paths src --ignore-src -r -s  # do a dry-run first
            rosdep install --from-paths src --ignore-src -r -y
      - name: Catkin build install
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          mkdir -p catkin_ws/src
          cd catkin_ws
          catkin config --install --cmake-args -DCMAKE_BUILD_TYPE=Release
          catkin build --no-status
          source install/setup.bash
      - name: test installed import
        run: |
          cd catkin_ws
          source install/setup.bash
          python --version
          # very basic test which may reveal a change made for python3 breaks here in python2
          python -c "import lifecycle.managed_node"
          python -c "from lifecycle.lifecycle_model import State, Transition, Result_Code, LifecycleModel"
      - name: Catkin build devel
        run: |
          cd catkin_ws
          rm -rf .catkin_tools build install logs
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin build --no-status
          source devel/setup.bash
      - name: test devel imports and example roslaunch
        run: |
          cd catkin_ws
          source devel/setup.bash
          # very basic test which may reveal a change made for python3 breaks here in python2
          python -c "import lifecycle.managed_node"
          python -c "from lifecycle.lifecycle_model import State, Transition, Result_Code, LifecycleModel"
          roslaunch `rospack find lifecycle_test_library`/examples/launch/lifecycle_test.launch
